"""fastapi-users

Revision ID: 5bcb92480fb0
Revises: 89a4a264c152
Create Date: 2024-07-19 02:49:09.046372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bcb92480fb0'
down_revision: Union[str, None] = '89a4a264c152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=320), nullable=False))
    op.add_column('users', sa.Column('code_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'code_id')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
