"""fastapi-users

Revision ID: 3173242d17a2
Revises: 5bcb92480fb0
Create Date: 2024-07-21 14:40:15.345179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3173242d17a2'
down_revision: Union[str, None] = '5bcb92480fb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_username', table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=320), nullable=False))
    op.create_index('ix_users_username', 'users', ['username'], unique=1)
    # ### end Alembic commands ###
